Siganushka\TransactionBundle\Entity\Transaction:
    attributes:
        id:
            groups: [transaction.item, transaction.collection]
        number:
            groups: [transaction.item, transaction.collection]
        amount:
            groups: [transaction.item, transaction.collection]
        payMethod:
            groups: [transaction.item, transaction.collection]
        payRequest:
            groups: [transaction.item, transaction.collection]
        payResponse:
            groups: [transaction.item, transaction.collection]
        successful:
            groups: [transaction.item, transaction.collection]
        type:
            groups: [transaction.item, transaction.collection]
        createdAt:
            groups: [transaction.item, transaction.collection]
        updatedAt:
            groups: [transaction.item, transaction.collection]
